/* eslint-disable no-irregular-whitespace */
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import './Audit Logs.css'
import { superAdminNavigation } from '../../components/superAdminNavigation'

const activities = [
  ['16 May 2025, 10:30 AM', 'Super Admin', 'Super Admin', 'Users', 'Created', 'Created new user John Doe', '192.168.1.10', 'Success'], ['16 May 2025, 10:15 AM', 'Sarah Wilson', 'Admin', 'Medicines', 'Updated', 'Updated medicine Paracetamol 650mg', '192.168.1.12', 'Success'], ['16 May 2025, 09:45 AM', 'Mike Johnson', 'Manager', 'Reports', 'Viewed', 'Viewed Sales Report', '192.168.1.15', 'Success'], ['16 May 2025, 09:30 AM', 'Priya Sharma', 'Pharmacist', 'Inventory', 'Added', 'Added stock for Amoxicillin 500mg', '192.168.1.18', 'Success'], ['16 May 2025, 09:10 AM', 'Super Admin', 'Super Admin', 'System Settings', 'Updated', 'Updated system configuration', '192.168.1.10', 'Success'], ['16 May 2025, 08:50 AM', 'John Doe', 'Admin', 'Users', 'Deleted', 'Deleted user Mike Johnson', '192.168.1.12', 'Failed'], ['16 May 2025, 08:30 AM', 'Anjali Patel', 'Pharmacist', 'Medicines', 'Updated', 'Updated price for Ibuprofen 400mg', '192.168.1.18', 'Success'], ['16 May 2025, 08:15 AM', 'Mike Johnson', 'Manager', 'Reports', 'Exported', 'Exported Inventory Report', '192.168.1.15', 'Success'], ['16 May 2025, 07:45 AM', 'Super Admin', 'Super Admin', 'Backup', 'Created', 'Created system backup', '192.168.1.10', 'Success'], ['16 May 2025, 07:30 AM', 'Sarah Wilson', 'Admin', 'Notifications', 'Sent', 'Sent notification to all users', '192.168.1.12', 'Success'], ['15 May 2025, 06:30 PM', 'John Doe', 'Admin', 'Users', 'Viewed', 'Viewed user permissions', '192.168.1.12', 'Success'], ['15 May 2025, 05:20 PM', 'Priya Sharma', 'Pharmacist', 'Inventory', 'Added', 'Received medicine stock', '192.168.1.18', 'Success'],
]
const defaults = { date: '01 May 2025 - 16 May 2025', user: 'All Users', module: 'All Modules', action: 'All Actions', status: 'All Status' }

function ActivityLogs() {
  const navigate = useNavigate()
  const [sidebar, setSidebar] = useState(false)
  const [profile, setProfile] = useState(false)
  const [filters, setFilters] = useState(defaults)
  const [page, setPage] = useState(1)
  const [toast, setToast] = useState('')
  const update = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1) }
  const filtered = useMemo(() => activities.filter((activity) => (filters.user === 'All Users' || activity[1] === filters.user) && (filters.module === 'All Modules' || activity[3] === filters.module) && (filters.action === 'All Actions' || activity[4] === filters.action) && (filters.status === 'All Status' || activity[7] === filters.status)), [filters])
  const visible = filtered.slice((page - 1) * 10, page * 10)
  const pages = Math.max(1, Math.ceil(filtered.length / 10))
  const notify = (message) => { setToast(message); window.setTimeout(() => setToast(''), 2400) }
  const optionSet = (index) => [...new Set(activities.map((activity) => activity[index]))]

  return <div className={`activity-page${sidebar ? ' activity-sidebar-open' : ''}`}>
    <aside className="activity-sidebar"><div className="activity-brand"><b>+</b><span><strong>Pharmacy System</strong><small>Super Admin</small></span></div><nav>{superAdminNavigation.map(({ label, path, icon }) => <button key={label} type="button" className={label === 'Audit Logs' ? 'active' : ''} onClick={() => navigate(path)}><i>{icon}</i>{label}</button>)}</nav><footer>⚙ <span><b>Pharmacy Management</b><small>System v1.0.0</small></span></footer></aside>
    <main className="activity-main"><header className="activity-header"><button className="activity-menu" type="button" onClick={() => setSidebar(!sidebar)}>☰</button><div><h1>Activity Logs</h1><p>Dashboard　›　Activity Logs</p></div><div className="activity-head-actions"><label>⌕<input placeholder="Search by user, action, module..." /></label><button type="button" className="activity-bell">♧<b>12</b></button><div className="activity-profile"><button type="button" onClick={() => setProfile(!profile)}><i>SA</i><span><b>Super Admin</b><small>Super Admin</small></span>⌄</button>{profile && <div><button type="button">My Profile</button><button type="button">Change Password</button><button type="button" onClick={() => navigate('/login')}>Logout</button></div>}</div></div></header>
      <section className="activity-stats">{[['▦', 'Total Activities', '2,458', 'All Time'], ['♙', 'Active Users', '156', 'This Month'], ['▣', "Today's Activities", '86', 'Today'], ['⚠', 'Critical Activities', '12', 'Require Attention']].map(([icon, label, value, note], index) => <article key={label}><i className={`activity-stat-${index}`}>{icon}</i><span><b>{label}</b><strong>{value}</strong><small>{note}</small></span></article>)}</section>
      <section className="activity-filters"><label>Date Range<input value={filters.date} onChange={(event) => update('date', event.target.value)} /></label>{[['User', 'user', 1, 'All Users'], ['Module', 'module', 3, 'All Modules'], ['Action', 'action', 4, 'All Actions'], ['Status', 'status', 7, 'All Status']].map(([label, key, index, all]) => <label key={key}>{label}<select value={filters[key]} onChange={(event) => update(key, event.target.value)}><option>{all}</option>{optionSet(index).map((item) => <option key={item}>{item}</option>)}</select></label>)}<button className="activity-apply" type="button" onClick={() => notify('Filters applied to activity logs.')}>⚱　Apply Filters</button><button className="activity-reset" type="button" onClick={() => { setFilters(defaults); setPage(1) }}>⟳　Reset</button></section>
      {toast && <p className="activity-toast">{toast}</p>}
      <section className="activity-content"><section className="activity-table-card"><h2>Activity Logs</h2><div className="activity-table-wrap"><table><thead><tr>{['Date & Time', 'User', 'Role', 'Module', 'Action', 'Description', 'IP Address', 'Status', 'More Actions'].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{visible.map((row) => <tr key={`${row[0]}-${row[1]}`}><td>{row[0]}</td><td><i className="log-avatar">{row[1].split(' ').map((name) => name[0]).join('')}</i><b>{row[1]}</b></td><td><span className={`role-${row[2].toLowerCase().replace(' ', '-')}`}>{row[2]}</span></td><td>{row[3]}</td><td><span className={`action-${row[4].toLowerCase()}`}>{row[4]}</span></td><td>{row[5]}</td><td>{row[6]}</td><td><span className={`log-status ${row[7].toLowerCase()}`}>{row[7]}</span></td><td><button className="more-log" type="button" onClick={() => notify(`Details opened for ${row[1]}.`)}>⋮</button></td></tr>)}</tbody></table></div><footer className="activity-pagination"><span>Showing {(page - 1) * 10 + 1} to {(page - 1) * 10 + visible.length} of 2,458 activities</span><select><option>10 per page</option></select><div><button type="button" onClick={() => setPage(Math.max(1, page - 1))}>‹</button>{Array.from({ length: Math.min(5, pages) }, (_, index) => <button type="button" className={page === index + 1 ? 'current' : ''} onClick={() => setPage(index + 1)} key={index}>{index + 1}</button>)}<button type="button" onClick={() => setPage(Math.min(pages, page + 1))}>›</button></div></footer></section><aside className="activity-right"><section><h2>Activity Summary</h2><div className="activity-donut"><span><small>Total</small><b>2,458</b></span></div><ul>{[['Success', '1,856 (75.5%)'], ['Failed', '142 (5.8%)'], ['Warning', '236 (9.6%)'], ['Info', '224 (9.1%)']].map(([label, value]) => <li key={label}><i />{label}<b>{value}</b></li>)}</ul></section><section><h2>Top Modules</h2>{[['Users', '658 (26.8%)'], ['Medicines', '542 (22.1%)'], ['Inventory', '412 (16.8%)'], ['Reports', '356 (14.5%)'], ['System Settings', '246 (10.0%)'], ['Others', '244 (9.8%)']].map(([label, value]) => <p key={label}><i>▤</i>{label}<b>{value}</b></p>)}</section><section><h2>Recent Critical Activities <button type="button" onClick={() => notify('Showing all critical activities.')}>View All</button></h2>{[['Failed login attempt', '10:20 AM'], ['Unauthorized access attempt', '09:15 AM'], ['Permission denied', '08:45 AM'], ['Data export failed', '08:30 AM']].map(([label, time]) => <p className="critical" key={label}><i>⚠</i>{label}<small>{time}</small></p>)}</section><section><h2>Activity Timeline <button type="button" onClick={() => notify('Activity timeline opened.')}>View Timeline</button></h2><p className="timeline">⌁　View detailed activity timeline</p></section></aside></section>
    </main>
  </div>
}

export default ActivityLogs
