/* eslint-disable no-irregular-whitespace, no-unused-vars */
import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import './Notifications.css'
import { superAdminNavigation } from '../../components/superAdminNavigation'

const navItems = superAdminNavigation.map(({ label, path }) => [label, path])
const initialNotifications = [
  ['Low Stock Alert', 'Paracetamol 650mg stock is below minimum level.', '16 May 2025, 10:30 AM', 'Inventory', 'cart', true], ['New User Created', 'A new pharmacist account was created by Super Admin.', '16 May 2025, 09:45 AM', 'User', 'user', false], ['System Backup Completed', 'Daily system backup completed successfully.', '16 May 2025, 08:30 AM', 'System', 'backup', false], ['Medicine Expiring Soon', '12 medicines will expire within the next 30 days.', '16 May 2025, 07:15 AM', 'Inventory', 'warning', true], ['Failed Login Attempt', 'Multiple failed login attempts detected from IP 192.168.1.45.', '15 May 2025, 11:20 PM', 'Security', 'security', true], ['System Update Available', 'A new system update is available. Please update to the latest version.', '15 May 2025, 10:10 PM', 'System', 'update', true], ['Monthly Sales Report Generated', 'Monthly sales report for April 2025 has been generated.', '15 May 2025, 09:00 PM', 'Report', 'report', true], ['Payment Received', 'Payment of Rs.25,430 received from Walk-in Customer.', '15 May 2025, 08:45 PM', 'Sales', 'payment', true], ['Stock Transfer Completed', 'Stock transfer to Kukatpally branch completed.', '15 May 2025, 07:10 PM', 'Inventory', 'cart', false], ['Prescription Dispensed', 'Prescription RX-10024 was successfully dispensed.', '15 May 2025, 06:30 PM', 'System', 'report', false], ['New Purchase Order', 'Purchase order PO-2491 has been created.', '15 May 2025, 05:45 PM', 'User', 'user', false], ['Account Access Changed', 'User permissions were updated.', '15 May 2025, 05:10 PM', 'Security', 'security', false],
]

function Toggle({ on, change }) { return <button className={`notification-toggle${on ? ' on' : ''}`} type="button" onClick={() => change(!on)} aria-pressed={on}><i /></button> }
function Notifications() {
  const navigate = useNavigate()
  const [sidebar, setSidebar] = useState(false); const [profile, setProfile] = useState(false); const [items, setItems] = useState(initialNotifications); const [query, setQuery] = useState(''); const [type, setType] = useState('All Types'); const [status, setStatus] = useState('All Status'); const [date, setDate] = useState('All Dates'); const [page, setPage] = useState(1); const [notice, setNotice] = useState(''); const [settings, setSettings] = useState({ email: true, sms: true, alerts: true, push: false })
  const notify = (message) => { setNotice(message); window.setTimeout(() => setNotice(''), 2200) }
  const filtered = useMemo(() => items.filter((item) => `${item[0]} ${item[1]} ${item[3]}`.toLowerCase().includes(query.toLowerCase()) && (type === 'All Types' || item[3] === type) && (status === 'All Status' || (status === 'Unread' ? item[5] : !item[5]))), [items, query, type, status])
  const visible = filtered.slice((page - 1) * 8, page * 8); const pages = Math.max(1, Math.ceil(filtered.length / 8)); const types = [...new Set(items.map((item) => item[3]))]
  const markRead = (index) => setItems((current) => current.map((item, itemIndex) => itemIndex === index ? [...item.slice(0, 5), false] : item))
  const markAllRead = () => { setItems((current) => current.map((item) => [...item.slice(0, 5), false])); notify('All notifications marked as read.') }
  const unread = items.filter((item) => item[5]).length
  return <div className={`notification-page${sidebar ? ' notification-sidebar-open' : ''}`}><aside className="notification-sidebar"><div className="notification-brand"><b>+</b><span><strong>Pharmacy System</strong><small>Super Admin</small></span></div><nav>{superAdminNavigation.map(({ label, path, icon }) => <button type="button" className={label === 'Notifications' ? 'active' : ''} onClick={() => navigate(path)} key={label}><i>{icon}</i>{label}</button>)}</nav><footer>⚙ <span><b>Pharmacy Management</b><small>System v1.0.0</small></span></footer></aside><main className="notification-main"><header className="notification-header"><button type="button" className="notification-menu" onClick={() => setSidebar(!sidebar)}>☰</button><div><h1>Notifications</h1><p>Dashboard　›　Notifications</p></div><div className="notification-head-actions"><label>⌕<input placeholder="Search by title, message, type..." /></label><button type="button" className="notification-bell">♧<b>12</b></button><div className="notification-profile"><button type="button" onClick={() => setProfile(!profile)}><i>SA</i><span><b>Super Admin</b><small>Super Admin</small></span>⌄</button>{profile && <div><button type="button">My Profile</button><button type="button">Change Password</button><button type="button" onClick={() => navigate('/login')}>Logout</button></div>}</div></div></header>
    <section className="notification-stats">{[['♧', 'Total Notifications', '248', 'All Time'], ['✉', 'Unread Notifications', `${unread}`, 'Unread'], ['▣', 'Today', '18', 'Today'], ['⚠', 'Critical Alerts', '5', 'Require Attention']].map(([icon, label, value, note], index) => <article key={label}><i className={`notification-stat-${index}`}>{icon}</i><span><b>{label}</b><strong>{value}</strong><small>{note}</small></span></article>)}</section>
    <section className="notification-filters"><label>⌕<input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder="Search notifications..." /></label><select value={type} onChange={(event) => { setType(event.target.value); setPage(1) }}><option>All Types</option>{types.map((item) => <option key={item}>{item}</option>)}</select><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option>All Status</option><option>Unread</option><option>Read</option></select><select value={date} onChange={(event) => setDate(event.target.value)}><option>All Dates</option><option>Today</option><option>This Week</option></select><button type="button" className="mark-all" onClick={markAllRead}>◉　Mark All as Read</button><button type="button" className="clear-all" onClick={() => { setItems([]); setPage(1); notify('All notifications cleared.') }}>▥　Clear All</button></section>{notice && <p className="notification-toast">{notice}</p>}
    <section className="notification-content"><section className="notification-list"><h2>All Notifications</h2>{visible.length ? visible.map((item, index) => { const originalIndex = items.indexOf(item); return <article className={item[5] ? 'unread' : ''} key={`${item[0]}-${item[2]}`}><em>{item[5] && '•'}</em><i className={`notification-icon ${item[4]}`}>{item[4] === 'cart' ? '⌘' : item[4] === 'user' ? '♙' : item[4] === 'backup' ? '☁' : item[4] === 'warning' ? '⚠' : item[4] === 'security' ? '◈' : item[4] === 'update' ? '↥' : item[4] === 'report' ? '▤' : '♧'}</i><span><b>{item[0]}</b><small>{item[1]}</small></span><time>{item[2]}</time><label className={item[3].toLowerCase()}>{item[3]}</label><button type="button" onClick={() => { markRead(originalIndex); notify(`${item[0]} marked as read.`) }}>⋮</button></article> }) : <p className="notification-empty">No notifications match your filters.</p>}<footer><span>Showing {visible.length ? (page - 1) * 8 + 1 : 0} to {(page - 1) * 8 + visible.length} of 248 notifications</span><select><option>10 per page</option></select><div><button type="button" onClick={() => setPage(Math.max(1, page - 1))}>‹</button>{Array.from({ length: Math.min(5, pages) }, (_, index) => <button type="button" className={page === index + 1 ? 'current' : ''} onClick={() => setPage(index + 1)} key={index}>{index + 1}</button>)}<button type="button" onClick={() => setPage(Math.min(pages, page + 1))}>›</button></div></footer></section><aside className="notification-right"><section><h2>Notification Summary</h2>{[['All Notifications', '248'], ['Unread', `${unread}`], ['Read', `${248 - unread}`], ['Critical Alerts', '5'], ['System', '68']].map(([label, value], index) => <p key={label}><i>{['◉', '✉', '◉', '⚠', '⚙'][index]}</i>{label}<b>{value}</b>›</p>)}</section><section><h2>Notification Settings</h2>{[['Email Notifications', 'Receive notifications via email', 'email'], ['SMS Notifications', 'Receive notifications via SMS', 'sms'], ['System Alerts', 'Receive important system alerts', 'alerts'], ['Push Notifications', 'Receive push notifications', 'push']].map(([label, copy, key]) => <label key={key}><i>▣</i><span><b>{label}</b><small>{copy}</small></span><Toggle on={settings[key]} change={(value) => setSettings((current) => ({ ...current, [key]: value }))} /></label>)}</section><section className="notification-info"><i>♧</i><span><b>Notifications</b><small>View and manage important pharmacy system alerts and notifications.</small></span></section></aside></section>
  </main></div>
}

export default Notifications
