import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { superAdminNavigation } from '../../components/superAdminNavigation'

const stats = [
  ['Total Branches', '24', 'Active Branches:', '21'], ['Total Users', '156', 'Active Users:', '142'], ['Total Medicines', '3,245', 'Active Medicines', ''],
  ['Total Sales (This Month)', '₹12,54,390', '↑ 12.5% vs Last Month', ''], ['Low Stock Alerts', '45', 'Critical Items:', '12'], ['Expiring Medicines', '32', 'Within 30 Days', ''],
]
const stock = [['Amoxicillin 500mg', '12', '50', 'Critical'], ['Paracetamol 650mg', '18', '40', 'Low'], ['Ibuprofen 400mg', '22', '50', 'Low'], ['Cetirizine 10mg', '15', '30', 'Low'], ['Omeprazole 20mg', '10', '25', 'Critical']]
const expiry = [['Azithromycin 500mg', 'AZT-1234', '20 May 2025', '5', 'Expired'], ['Pantoprazole 40mg', 'PNT-5678', '25 May 2025', '10', 'Critical'], ['Diclofenac 50mg', 'DIC-9101', '28 May 2025', '13', 'Critical'], ['Cefixime 200mg', 'CFI-1121', '30 May 2025', '15', 'Low'], ['Metformin 500mg', 'MET-3141', '02 Jun 2025', '18', 'Low']]
const prescriptions = [['RX-10024', 'Ravi Kumar', 'Dr. John Smith', 'Branch 1', '15 May 2025, 11:30 AM', '₹1,250.00', 'Dispensed'], ['RX-10023', 'Sneha Reddy', 'Dr. Emily Davis', 'Branch 2', '15 May 2025, 10:15 AM', '₹850.00', 'Pending'], ['RX-10022', 'Vikram Singh', 'Dr. Michael Brown', 'Branch 3', '15 May 2025, 09:45 AM', '₹1,560.00', 'Dispensed'], ['RX-10021', 'Anita Sharma', 'Dr. Sarah Wilson', 'Branch 1', '14 May 2025, 04:20 PM', '₹950.00', 'Dispensed']]
const transactions = [['INV-20054', 'Branch 1', '15 May 2025', '₹2,350.00', 'UPI', 'Paid'], ['INV-20053', 'Branch 2', '15 May 2025', '₹1,890.00', 'Card', 'Paid'], ['INV-20052', 'Branch 3', '15 May 2025', '₹950.00', 'Cash', 'Paid'], ['INV-20051', 'Branch 1', '14 May 2025', '₹1,450.00', 'UPI', 'Paid']]
const activities = [['New branch “Green Pharmacy” added', '10 mins ago'], ['User “John Doe” created', '25 mins ago'], ['Medicine “Paracetamol 500mg” added', '45 mins ago'], ['Low stock alert for “Amoxicillin 500mg”', '1 hour ago'], ['Monthly sales report generated', '2 hours ago']]
const branches = [['Branch 1', '₹3,24,560 (25.8%)'], ['Branch 2', '₹2,45,780 (19.6%)'], ['Branch 3', '₹2,10,320 (16.8%)'], ['Branch 4', '₹1,85,600 (14.8%)'], ['Others', '₹2,88,130 (23.0%)']]

function Icon({ children }) { return <svg className="admin-icon" viewBox="0 0 24 24" fill="none" aria-hidden="true">{children}</svg> }
function Status({ value }) { return <span className={`status-badge status-${value.toLowerCase()}`}>{value}</span> }
function Table({ headers, rows }) { return <div className="dashboard-table-wrap"><table className="dashboard-table"><thead><tr>{headers.map((v) => <th key={v}>{v}</th>)}</tr></thead><tbody>{rows.map((row) => <tr key={row[0]}>{row.map((cell, index) => <td key={`${row[0]}-${index}`}>{index === row.length - 1 && ['Critical', 'Low', 'Expired', 'Dispensed', 'Pending', 'Paid'].includes(cell) ? <Status value={cell} /> : cell}</td>)}</tr>)}</tbody></table></div> }
function Panel({ title, children, viewAll }) { return <section className="dashboard-card"><div className="dashboard-card-heading"><h2>{title}</h2>{viewAll && <button className="view-all-button" type="button">View All</button>}</div>{children}</section> }

function SuperAdminDashboard() {
  const navigate = useNavigate(); const [open, setOpen] = useState(false); const [menu, setMenu] = useState(false)
  return <div className={`admin-shell${open ? ' sidebar-open' : ''}`}>
    <aside className="admin-sidebar"><div className="admin-brand"><span className="admin-brand-mark">+</span><div><strong>Pharmacy System</strong><small>Super Admin</small></div></div><nav className="admin-nav">{superAdminNavigation.map(({ label, path, icon }) => <button type="button" onClick={() => navigate(path)} className={`admin-nav-link${label === 'Dashboard' ? ' is-active' : ''}`} key={label}><span className="nav-icon" aria-hidden="true">{icon}</span><span>{label}</span></button>)}</nav><div className="admin-sidebar-footer"><span className="footer-badge">+</span><div><strong>Pharmacy Management</strong><small>System v1.0.0</small></div></div></aside>
    <main className="admin-main"><header className="admin-topbar"><button className="topbar-menu" type="button" onClick={() => setOpen(!open)}><Icon><path d="M4 6h16M4 12h16M4 18h16" /></Icon></button><div className="topbar-title"><h1>Super Admin Dashboard</h1><p>Welcome back! Here&apos;s what&apos;s happening in your pharmacy system.</p></div><div className="admin-topbar-actions"><label className="dashboard-search"><Icon><circle cx="11" cy="11" r="6" /><path d="m16 16 4 4" /></Icon><input placeholder="Search here..." /></label><button className="notification-button" type="button"><Icon><path d="M6 9a6 6 0 0 1 12 0c0 7 2 7 2 9H4c0-2 2-2-2-9" /><path d="M10 21h4" /></Icon><b>12</b></button><div className="profile-wrap"><button className="admin-profile" type="button" onClick={() => setMenu(!menu)}><span className="profile-avatar">SA</span><span className="profile-copy"><strong>Super Admin</strong><small>Super Admin</small></span>⌄</button>{menu && <div className="profile-menu"><button>My Profile</button><button>Change Password</button><button onClick={() => navigate('/login')}>Logout</button></div>}</div></div></header>
      <section className="summary-grid">{stats.map(([title, value, note, detail], i) => <article className={`summary-card summary-card-${i + 1}`} key={title}><span className="summary-icon">{i === 3 ? '₹' : i === 4 ? '!' : '+'}</span><div><p>{title}</p><strong>{value}</strong><small>{note} {detail && <b>{detail}</b>}</small></div></article>)}</section>
      <section className="analytics-grid"><Panel title="Sales Overview"><div className="panel-controls"><button>This Month⌄</button></div><div className="sales-chart"><span>₹20L</span><span>₹15L</span><span>₹10L</span><span>₹5L</span><span>₹0</span><svg viewBox="0 0 600 180" preserveAspectRatio="none"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stopColor="#1673f1" stopOpacity=".25"/><stop offset="1" stopColor="#1673f1" stopOpacity="0"/></linearGradient></defs><path d="M25 132 L85 65 L145 105 L205 125 L265 112 L325 132 L385 105 L445 112 L505 62 L550 94 L590 54 L590 175 L25 175Z" fill="url(#area)"/><path d="M25 132 L85 65 L145 105 L205 125 L265 112 L325 132 L385 105 L445 112 L505 62 L550 94 L590 54" fill="none" stroke="#126cf0" strokeWidth="3"/>{[25,85,145,205,265,325,385,445,505,550,590].map((x, i) => <circle key={x} cx={x} cy={[132,65,105,125,112,132,105,112,62,94,54][i]} r="4" fill="#126cf0" stroke="white" strokeWidth="2"/>)}</svg><div className="chart-labels"><span>01 May</span><span>05 May</span><span>10 May</span><span>15 May</span><span>20 May</span><span>25 May</span><span>31 May</span></div></div></Panel><Panel title="Branch Performance"><div className="panel-controls"><button>This Month⌄</button></div><div className="branch-chart"><div className="donut"><div><small>Total Sales</small><strong>₹12,54,390</strong></div></div><ul>{branches.map(([name, amount], index) => <li key={name}><i className={`branch-dot dot-${index}`} /><span>{name}</span><b>{amount}</b></li>)}</ul></div></Panel></section>
      <section className="mid-grid"><Panel title="Recent Activity" viewAll><div className="activity-list">{activities.map(([text, time]) => <div key={text}><span className="activity-icon">+</span><p>{text}</p><small>{time}</small></div>)}</div></Panel><Panel title="Low Stock Medicines" viewAll><Table headers={['Medicine Name', 'Current Stock', 'Min. Stock', 'Status']} rows={stock} /></Panel><Panel title="Expiry Alerts" viewAll><Table headers={['Medicine Name', 'Batch No.', 'Expiry Date', 'Days Left', 'Status']} rows={expiry} /></Panel></section>
      <section className="bottom-grid"><Panel title="Recent Prescriptions"><Table headers={['Prescription ID', 'Patient Name', 'Doctor Name', 'Branch', 'Date', 'Total Amount', 'Status']} rows={prescriptions} /></Panel><Panel title="Recent Transactions" viewAll><Table headers={['Invoice No.', 'Branch', 'Date', 'Amount', 'Payment Mode', 'Status']} rows={transactions} /></Panel></section>
    </main>
  </div>
}
export default SuperAdminDashboard
