import { useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { superAdminNavigation } from '../../components/superAdminNavigation'

const people = [
  ['John Doe', 'john.doe@example.com', 'Super Admin', 'Head Office', 'Active', '15 May 2025, 10:30 AM'], ['Sarah Wilson', 'sarah.wilson@example.com', 'Admin', 'Head Office', 'Active', '15 May 2025, 09:15 AM'], ['Michael Brown', 'michael.brown@example.com', 'Manager', 'Branch 1', 'Active', '14 May 2025, 05:45 PM'], ['Emily Davis', 'emily.davis@example.com', 'Supervisor', 'Branch 1', 'Active', '14 May 2025, 02:30 PM'], ['David Johnson', 'david.johnson@example.com', 'Pharmacist', 'Branch 2', 'Active', '14 May 2025, 11:20 AM'], ['Lisa Martinez', 'lisa.martinez@example.com', 'Pharmacist', 'Branch 3', 'Inactive', '10 May 2025, 04:10 PM'], ['Robert Taylor', 'robert.taylor@example.com', 'Supervisor', 'Branch 2', 'Active', '13 May 2025, 03:50 PM'], ['Jennifer Anderson', 'jennifer.anderson@example.com', 'Manager', 'Branch 3', 'Active', '12 May 2025, 09:40 AM'], ['Nora Roberts', 'nora.roberts@example.com', 'Admin', 'Branch 1', 'Active', '11 May 2025, 09:10 AM'], ['Ajay Kumar', 'ajay.kumar@example.com', 'Pharmacist', 'Branch 2', 'Inactive', '10 May 2025, 04:00 PM'],
]
const initials = (value) => value.split(' ').map((word) => word[0]).join('')

function UsersPermissions() {
  const navigate = useNavigate(); const [query, setQuery] = useState(''); const [role, setRole] = useState('All Roles'); const [branch, setBranch] = useState('All Branches'); const [status, setStatus] = useState('All Status'); const [page, setPage] = useState(1); const [selected, setSelected] = useState(null); const [edit, setEdit] = useState(null); const [menu, setMenu] = useState(null); const [sidebar, setSidebar] = useState(false)
  const filtered = useMemo(() => people.filter((person) => `${person[0]} ${person[1]}`.toLowerCase().includes(query.toLowerCase()) && (role === 'All Roles' || person[2] === role) && (branch === 'All Branches' || person[3] === branch) && (status === 'All Status' || person[4] === status)), [query, role, branch, status])
  const visible = filtered.slice((page - 1) * 8, page * 8); const pages = Math.max(1, Math.ceil(filtered.length / 8))
  const resetFilters = () => { setQuery(''); setRole('All Roles'); setBranch('All Branches'); setStatus('All Status'); setPage(1) }
  return <div className={`users-page${sidebar ? ' users-sidebar-open' : ''}`}>
    <aside className="users-sidebar"><div className="users-brand"><b>+</b><div><strong>Pharmacy System</strong><small>Super Admin</small></div></div><nav>{superAdminNavigation.map(({ label, path, icon }) => <button type="button" onClick={() => navigate(path)} className={label === 'Users & Permissions' ? 'active' : ''} key={label}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav><div className="users-footer">⚙ <span><b>Pharmacy Management</b><small>System v1.0.0</small></span></div></aside>
    <main className="users-main"><header className="users-header"><button type="button" className="users-hamburger" onClick={() => setSidebar(!sidebar)}>☰</button><div><h1>Users &amp; Permissions</h1><p>Dashboard › Users &amp; Permissions</p></div><div className="users-header-right"><label>⌕ <input placeholder="Search here..." /></label><span className="users-bell">♧<b>12</b></span><span className="users-avatar">SA</span><span><b>Super Admin</b><small>Super Admin</small></span>⌄</div></header>
      <section className="users-summary">{[['Total Users', '156', 'Active Users: ', '142'], ['Roles', '5', 'Active Roles: ', '5'], ['Permissions', '78', 'System Permissions', ''], ['New Users (This Month)', '18', 'vs Last Month　↑ ', '12.5%']].map(([title, value, note, accent], index) => <article key={title}><i className={`user-stat user-stat-${index}`}>+</i><div><p>{title}</p><strong>{value}</strong><small>{note}<b>{accent}</b></small></div></article>)}</section>
      <section className="users-content"><div className="users-list-card"><div className="users-filters"><label>⌕ <input value={query} onChange={(event) => { setQuery(event.target.value); setPage(1) }} placeholder="Search by name, email or phone..." /></label><select value={role} onChange={(event) => { setRole(event.target.value); setPage(1) }}><option>All Roles</option>{['Super Admin', 'Admin', 'Manager', 'Supervisor', 'Pharmacist'].map((v) => <option key={v}>{v}</option>)}</select><select value={branch} onChange={(event) => { setBranch(event.target.value); setPage(1) }}><option>All Branches</option>{['Head Office', 'Branch 1', 'Branch 2', 'Branch 3'].map((v) => <option key={v}>{v}</option>)}</select><select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1) }}><option>All Status</option><option>Active</option><option>Inactive</option></select><button type="button" onClick={resetFilters}>⌑ Filters</button></div><div className="users-table-wrap"><table className="users-table"><thead><tr>{['Name', 'Email', 'Role', 'Branch', 'Status', 'Last Login', 'Actions'].map((heading) => <th key={heading}>{heading}</th>)}</tr></thead><tbody>{visible.map((person) => <tr key={person[1]}><td><span className="user-avatar">{initials(person[0])}</span><b>{person[0]}</b><small>+91 98765 43210</small></td><td>{person[1]}</td><td><span className={`role-tag role-${person[2].toLowerCase().replace(' ', '-')}`}>{person[2]}</span></td><td>{person[3]}</td><td><span className={`user-status ${person[4].toLowerCase()}`}>{person[4]}</span></td><td>{person[5]}</td><td className="user-actions"><button onClick={() => setSelected(person)} type="button">◉</button><button onClick={() => setEdit(person)} type="button">✎</button><button onClick={() => setMenu(menu === person[1] ? null : person[1])} type="button">⋮</button>{menu === person[1] && <div className="row-menu"><button onClick={() => setSelected(person)}>View details</button><button onClick={() => setEdit(person)}>Edit user</button></div>}</td></tr>)}</tbody></table></div><footer className="users-pagination"><span>Showing {visible.length ? (page - 1) * 8 + 1 : 0} to {(page - 1) * 8 + visible.length} of {filtered.length} users</span><select><option>10 per page</option></select><div><button onClick={() => setPage(Math.max(1, page - 1))}>‹</button>{Array.from({ length: pages }, (_, i) => <button key={i} onClick={() => setPage(i + 1)} className={page === i + 1 ? 'current' : ''}>{i + 1}</button>)}<button onClick={() => setPage(Math.min(pages, page + 1))}>›</button></div></footer></div>
        <aside className="users-right"><section><h2>Role Summary</h2><div className="role-chart"><div><small>Total</small><strong>5</strong></div></div><ul>{['Super Admin', 'Admin', 'Manager', 'Supervisor', 'Pharmacist'].map((name) => <li key={name}><i />{name}<b>1</b></li>)}</ul></section><section><h2>Permissions Overview</h2><div className="permission-metrics"><span><b>78</b>Total Permissions</span><span><b>42</b>Module Permissions</span><span><b>36</b>Action Permissions</span></div></section><section><h2>Quick Actions</h2>{['Manage Roles', 'Manage Permissions', 'Import Users'].map((name) => <button className="quick-action" type="button" key={name}><i>+</i><span><b>{name}</b><small>{name === 'Import Users' ? 'Import users from CSV file' : name === 'Manage Roles' ? 'Create and manage user roles' : 'Configure system permissions'}</small></span>›</button>)}</section></aside></section>
      <section className="roles-info"><i>i</i><div><b>User Roles &amp; Permissions</b><p>Manage system users, assign roles, and configure permissions to control access to different modules and features.</p></div><button type="button">View Role Matrix</button></section>
    </main>{selected && <div className="user-modal"><div><button onClick={() => setSelected(null)}>×</button><h2>{selected[0]}</h2><p>{selected[1]}</p><p><b>Role:</b> {selected[2]}</p><p><b>Branch:</b> {selected[3]}</p><p><b>Status:</b> {selected[4]}</p></div></div>}{edit && <div className="user-modal"><div><button onClick={() => setEdit(null)}>×</button><h2>Edit {edit[0]}</h2><label>Name<input defaultValue={edit[0]} /></label><label>Role<select defaultValue={edit[2]}>{['Super Admin', 'Admin', 'Manager', 'Supervisor', 'Pharmacist'].map((v) => <option key={v}>{v}</option>)}</select></label><button className="modal-save" onClick={() => setEdit(null)}>Save changes</button></div></div>}</div>
}
export default UsersPermissions
